version: "3"
services:
  client:
    container_name: dcs-homepage
    stdin_open: true
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: Dockerfile-codesandbox
    ports:
      - "3000:3000"
