version: "3"
services:
  client:
    container_name: dcs-homepage
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./templates/home.tmpl
        target: /data/gitea/templates/home.tmpl
      - type: bind
        source: ./conf/app.ini-codesandbox
        target: /data/gitea/conf/app.ini

