version: "3"
services:
  client:
    container_name: dcs-homepage
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "${PWD}/templates:/data/gitea/templates"
      - "${PWD}/options/locale:/data/gitea/options/locale"
      - "${PWD}/conf/app.ini:/data/gitea/conf/app.ini"

