FROM unfoldingword/dcs:latest-qa

ENV USER richmahn
ENV GITEA_CUSTOM /data/gitea 

WORKDIR /data/gitea

RUN mkdir /data/gitea/conf
RUN mkdir /data/gitea/templates
COPY ./conf/app.ini /data/gitea/conf
COPY ./templates/home.tmpl /data/gitea/templates
